USE [DisneyQuizApp]
GO

/****** Object:  Table [Anagrafica].[Utenti]    Script Date: 03/09/2019 10:38:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Anagrafica].[Utenti](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](30) NOT NULL,
	[PASSWORD] [nvarchar](30) NOT NULL,
	[MONETE] [int] NOT NULL,
 CONSTRAINT [PK_ANAGRAFICA_UTENTI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


