USE [DisneyQuizApp]
GO

/****** Object:  Table [Anagrafica].[Livelli]    Script Date: 03/09/2019 10:37:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Anagrafica].[Livelli](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NUMERO] [int] NOT NULL,
 CONSTRAINT [PK_ANAGRAFICA_LIVELLI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[NUMERO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

insert into Anagrafica.Livelli (ID, NUMERO)
values (1,1)


