USE [DisneyQuizApp]
GO

/****** Object:  Table [Anagrafica].[Personaggi]    Script Date: 03/09/2019 10:37:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Anagrafica].[Personaggi](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_LIVELLO] [int] NOT NULL,
	[NOME] [nvarchar](50) NOT NULL,
	[FILM] [nvarchar](50) NOT NULL,
	[PREMIO] [int] NOT NULL,
	[PREZZO] [int] NOT NULL,
	[URL_IMMAGINE] nvarchar(200) NULL,
 CONSTRAINT [PK_ANAGRAFICA_PERSONAGGI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[NOME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Anagrafica].[Personaggi]  WITH CHECK ADD  CONSTRAINT [FK_ANAGRAFICA_PERSONAGGI] FOREIGN KEY([ID_LIVELLO])
REFERENCES [Anagrafica].[Livelli] ([ID])
GO

ALTER TABLE [Anagrafica].[Personaggi] CHECK CONSTRAINT [FK_ANAGRAFICA_PERSONAGGI]
GO


