USE [DisneyQuizApp]
GO

/****** Object:  Table [Relazioni].[RisoluzioniPersonaggi]    Script Date: 03/09/2019 10:38:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Relazioni].[RisoluzioniPersonaggi](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_UTENTE] [int] NOT NULL,
	[ID_PERSONAGGIO] [int] NOT NULL,
 CONSTRAINT [PK_RELAZIONI_RISOLUZIONIPERSONAGGI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Relazioni].[RisoluzioniPersonaggi]  WITH CHECK ADD  CONSTRAINT [FK_RELAZIONI_RISOLUZIONIPERSONAGGI_PERSONAGGIO] FOREIGN KEY([ID_PERSONAGGIO])
REFERENCES [Anagrafica].[Personaggi] ([ID])
GO

ALTER TABLE [Relazioni].[RisoluzioniPersonaggi] CHECK CONSTRAINT [FK_RELAZIONI_RISOLUZIONIPERSONAGGI_PERSONAGGIO]
GO

ALTER TABLE [Relazioni].[RisoluzioniPersonaggi]  WITH CHECK ADD  CONSTRAINT [FK_RELAZIONI_RISOLUZIONIPERSONAGGI_UTENTE] FOREIGN KEY([ID_UTENTE])
REFERENCES [Anagrafica].[Utenti] ([ID])
GO

ALTER TABLE [Relazioni].[RisoluzioniPersonaggi] CHECK CONSTRAINT [FK_RELAZIONI_RISOLUZIONIPERSONAGGI_UTENTE]
GO


